import React from "react";

function Loading() {
  return (
    <>
      <div className="overlay">
        <div className="loadingio-spinner-ripple-5t4o07tq2kw">
          <div className="ldio-uqhn0qjk1x">
            <div />
            <div />
          </div>
        </div>
      </div>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html:
            "\n      @keyframes ldio-uqhn0qjk1x {\n        0% {\n          top: 96px;\n          left: 96px;\n          width: 0;\n          height: 0;\n          opacity: 1;\n        }\n        100% {\n          top: 36px;\n          left: 36px;\n          width: 120px;\n          height: 120px;\n          opacity: 0;\n        }\n      }\n      .overlay {\n        position: fixed;\n        inset: 0;\n        background-color: rgba(125, 215, 235, 0.386);\n        display: flex;\n        justify-content: center;\n        align-items: center;\n      }\n      .ldio-uqhn0qjk1x div {\n        position: absolute;\n        border-width: 4px;\n        border-style: solid;\n        opacity: 1;\n        border-radius: 50%;\n        animation: ldio-uqhn0qjk1x 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;\n      }\n      .ldio-uqhn0qjk1x div:nth-child(1) {\n        border-color: #e90c59;\n        animation-delay: 0s;\n      }\n      .ldio-uqhn0qjk1x div:nth-child(2) {\n        border-color: #46dff0;\n        animation-delay: -0.5s;\n      }\n      .loadingio-spinner-ripple-5t4o07tq2kw {\n        width: 200px;\n        height: 200px;\n        display: inline-block;\n        overflow: hidden;\n      }\n      .ldio-uqhn0qjk1x {\n        width: 100%;\n        height: 100%;\n        position: relative;\n        transform: translateZ(0) scale(1);\n        backface-visibility: hidden;\n        transform-origin: 0 0; /* see note above */\n      }\n      .ldio-uqhn0qjk1x div {\n        box-sizing: content-box;\n      }\n      /* generated by https://loading.io/ */\n    ",
        }}
      />
    </>
  );
}

export default Loading;
