import React, { Component } from "react";

export class Loading extends Component {
  render() {
    return (
      <>
        <div className="overlay">
          <div className="loadingio-spinner-eclipse-tdxmhh22p8">
            <div className="ldio-0skrctsnq2lg">
              <div />
            </div>
          </div>
        </div>
        <style
          type="text/css"
          dangerouslySetInnerHTML={{
            __html:
              "\n      @keyframes ldio-0skrctsnq2lg {\n        0% {\n          transform: rotate(0deg);\n        }\n        50% {\n          transform: rotate(180deg);\n        }\n        100% {\n          transform: rotate(360deg);\n        }\n      }\n      @keyframes overlay {\n        0% {\n          opacity: 0;\n        }\n        100% {\n          opacity: 1;\n        }\n      }\n      .ldio-0skrctsnq2lg div {\n        position: absolute;\n        animation: ldio-0skrctsnq2lg 1s linear infinite;\n        width: 120px;\n        height: 120px;\n        top: 20px;\n        left: 20px;\n        border-radius: 50%;\n        box-shadow: 0 4px 0 0 #0f766e;\n        transform-origin: 80px 82px;\n      }\n      .loadingio-spinner-eclipse-tdxmhh22p8 {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        translate: -50% -50%;\n        width: 180px;\n        height: 180px;\n        display: inline-block;\n        overflow: hidden;\n      }\n      .ldio-0skrctsnq2lg {\n        width: 100%;\n        height: 100%;\n        position: relative;\n        transform: translateZ(0) scale(1);\n        backface-visibility: hidden;\n        transform-origin: 0 0; /* see note above */\n      }\n      .overlay {\n        position: fixed;\n        inset: 0;\n        background-color: rgba(206, 202, 202, 0.354);\n        opacity: 1;\n        animation: overlay;\n        animation-duration: 1s;\n      }\n      .ldio-0skrctsnq2lg div {\n        box-sizing: content-box;\n      }\n      /* generated by https://loading.io/ */\n    ",
          }}
        />
      </>
    );
  }
}

export default Loading;
